services:
  cassandra-node1:
    image: cassandra:4.1
    container_name: 2025GRP01-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=2025GRP01
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_LISTEN_ADDRESS=172.28.0.2  # Explicitly set listen address
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # Allow external connections
    networks:
      cassandra-net:
        ipv4_address: 172.28.0.2

  cassandra-node2:
    image: cassandra:4.1
    container_name: 2025GRP01-node2
    environment:
      - CASSANDRA_CLUSTER_NAME=2025GRP01
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
      - CASSANDRA_SEEDS=172.28.0.2  
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_LISTEN_ADDRESS=172.28.0.3  
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  
    depends_on:
      - cassandra-node1
    networks:
      cassandra-net:
        ipv4_address: 172.28.0.3

  cassandra-node3:
    image: cassandra:4.1
    container_name: 2025GRP01-node3
    environment:
      - CASSANDRA_CLUSTER_NAME=2025GRP01
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
      - CASSANDRA_SEEDS=172.28.0.2  
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_LISTEN_ADDRESS=172.28.0.4  
      - CASSANDRA_RPC_ADDRESS=0.0.0.0 
    depends_on:
      - cassandra-node1
    networks:
      cassandra-net:
        ipv4_address: 172.28.0.4

networks:
  cassandra-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
